### ISSUE TITLE
Weird issue with Serial commands

### ISSUE THREAD

**Issue by Erutan409** [mike-matera/ArduinoSTL#10]
After [swapping out another library for you'rs](https://github.com/mike-matera/ArduinoSTL/issues/9), I noticed an issue with `Serial.println()` invocations.  They don't seem to work outside of the `setup` method.  And if I include `Serial.println()` commands with other functions contained in previously working lambdas on timed intervals, it prevents them from functioning.

Have you encountered this before?

**Comment by mike-matera** [comment]
Can you give me sample code? 

Serial.println() still works in my testing. However, you should be careful using print statements in interrupt handlers. The standard libraries are not reentrant and that will cause problems.
