### ISSUE TITLE
Reverse order of std::swap_range and std::iter_swap

### ISSUE THREAD

**Issue by jwellbelove** [mike-matera/ArduinoSTL#14]
There is an issue when compiling for a Genuino Zero.
It does not like the fact that the definition for **std::iter_swap** comes before **std::swap_range** (which uses it).
The order two functions should be swapped.

**Comment by mike-matera** [comment]
Thanks for the report. It works for me when I try to build. What version of Arduino are you using? Also, could you provide a sample sketch?
