### ISSUE TITLE
Facing problem with usase of functional

### ISSUE THREAD

**Issue by arihantdaga** [mike-matera/ArduinoSTL#18]
`
typedef std::function<void(uint8_t pin, uint8_t event, uint8_t count, uint16_t length)> TDebounceEventCallback;

`

I have a library which is using function templates like this, and i am little new with this type of code in C++. But i found that in the arduinoSTL library there is no template for function instead only for unary_function and binary_function... 
Can somebody help me here how can i use function of that sort...

**Comment by mike-matera** [comment]
I'm not very familiar with the functional code. What I can tell you is that the STL implementation comes from here: 
https://cxx.uclibc.org/index.html
I have just done a little work to make is easy to use in Arduino and added some streams support. The upstream project hasn't had a revision in a while. I'm always happy to take PRs.

**Comment by arihantdaga** [comment]
@mike-matera  Thanks anyway...

**Comment by cpk1971** [comment]
another C++11 thingy that makes use of lambdas a lot more friendly

it's not 100% necessary--you can still use function pointers...but function<> makes it agnostic between lambdas, function pointers, overloads of () and so on
