### ISSUE TITLE
Problem with %f in printf and scanf

### ISSUE THREAD

**Issue by evandrorech** [mike-matera/ArduinoSTL#19]
I'm trying to use printf() and scanf() with %f format specifier, but they not work. For scanf(), the program does not wait for the serial and for printf(), it prints the float number as a "?".

Using cin and cout it works correctly, but with only 2 digits of precision.

I'm using an Arduino Nano with ATMEGA328. 

Thanks!

**Comment by mike-matera** [comment]
The printf() and scanf() functions come from the C library and do not support floats on the AVR architecture. The precision of cin is more than two places, but cout only ever prints two places. This is a known limitation. 

Sorry!

**Comment by evandrorech** [comment]
Thanks!
