### ISSUE TITLE
Issues using map

### ISSUE THREAD

**Issue by radsolution** [mike-matera/ArduinoSTL#25]
Hi Mike.
I'm using your library, and everything seems to work except map.
Here's my declaration in a .h file:
`std::map<int, edSession*> sessions;`
and the error I get is:
`this declaration has no storage class or type specifier`
What is wrong, please?
I also can't see how string, map and vector get pulled into my .h file when I add:
`#include <ArduinoSTL.h>`
Can you please explain? I'm fairly new to Arduino/C/C++
radsolution@yahoo.co.uk

**Comment by mike-matera** [comment]
Hello! 

Don't forget to include `map`. Here's a sketch that works: 

```c++
#include <ArduinoSTL.h>
#include <map>

std::map<std::string, std::string> m; 

void setup() {
  m["hello"] = "world";
}

void loop() {
  std::cout << m["hello"] << std::endl;
}
```

**Comment by radsolution** [comment]
Thanks Mike
    On Friday, 7 December 2018, 15:44:25 GMT, Mike Matera <notifications@github.com> wrote:  
 
 
Hello!

Don't forget to include map. Here's a sketch that works:
#include <ArduinoSTL.h>
#include <map>

std::map<std::string, std::string> m; 

void setup() {
  m["hello"] = "world";
}

void loop() {
  std::cout << m["hello"] << std::endl;
}
