### ISSUE TITLE
It can not be used,and I do not know how to fix it

### ISSUE THREAD

**Issue by shjdgwj** [mike-matera/ArduinoSTL#44]
In file included from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/string:25:0,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/locale:22,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/ios:22,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/serstream:18,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/ArduinoSTL.h:12,

                 from E:\arduino\project\Main\Main.ino:1:

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/vector:43:94: error: macro "swap" passed 4 arguments, but takes just 2

  template <class T, class Allocator> void swap(vector<T,Allocator>& x, vector<T,Allocator>& y);
    
E:\Arduino\libraries\ArduinoSTL-1.1.0\src/vector:523:106: error: macro "swap" passed 4 arguments, but takes just 2

  template <class T, class Allocator> _UCXXEXPORT void swap(vector<T,Allocator>& x, vector<T,Allocator>& y){

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/vector:524:11: error: macro "swap" requires 2 arguments, but only 1 given

   x.swap(y);

In file included from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/locale:22:0,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/ios:22,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/serstream:18,

                 from E:\Arduino\libraries\ArduinoSTL-1.1.0\src/ArduinoSTL.h:12,

                 from c:\users\gwj\appdata\local\temp\arduino_build_132997\sketch\define.h:12,

                 from E:\arduino\project\Main\Main.ino:1:

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/string:401:48: error: macro "swap" passed 3 arguments, but takes just 2

  _UCXXEXPORT void swap(basic_string<Ch,Tr,A>& s){

                                                ^

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/string:404:24: error: macro "swap" requires 2 arguments, but only 1 given

   vector<Ch, A>::swap(s);

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/string:1003:91: error: macro "swap" passed 6 arguments, but takes just 2

  swap(basic_string<charT,traits,Allocator>& lhs, basic_string<charT,traits,Allocator>& rhs)

                                                                                           ^

E:\Arduino\libraries\ArduinoSTL-1.1.0\src/string:1005:14: error: macro "swap" requires 2 arguments, but only 1 given

  lhs.swap(rhs);

**Comment by mike-matera** [comment]
It's fixed in the latest release.
