### ISSUE TITLE
C++11 std::function support

### ISSUE THREAD

**Issue by codinghusi** [mike-matera/ArduinoSTL#45]
Any plans?

**Comment by nobodyinperson** [comment]
@codinghusi I guess @mike-matera can't do much about this, `ArduinoSTL` is just a port of [uClibC++](https://cxx.uclibc.org/faq.html), so this question should rather be directed at [its developer](https://cxx.uclibc.org/contact.html).

**Comment by mike-matera** [comment]
Thsnk @nobodyinperson. The limitation is from uClibc++
