### ISSUE TITLE
Suggestion: correct Missing info in Documentation

### ISSUE THREAD

**Issue by cems2** [mike-matera/ArduinoSTL#54]
Hello, this is pretty simple as issues go but....

there's Mike-Matera/ArduinoSTL and Mike-matera/avr_stl

1.  documentation for avr_stl is identical to ArduinoSTL even down to saying `#include <ArduinoSTL>` and not as might be expected `#include <avr_stl>`

2.  There's no indication what distinuishes these two libraries.  Both have similar recent commits and both are available on the Arduino applications library manager.  

Maybe indicate in the documentation what differs and what the use cases are intended for.

**Comment by mike-matera** [comment]
Hi! The other repo you're thinking of is: ciband/avr_stl

I don't have any control over that. He forked this one because I hadn't made changes in a while!
