### ISSUE TITLE
Support for Error Handing for using with Eclipse plugin

### ISSUE THREAD

**Issue by davidhood2** [mike-matera/ArduinoSTL#6]
No errors at all when using with the Arduino IDE.
However, I'm one of those who prefers to use the more expansive Eclipse IDE + plugin.
I imported the source code library with no issues, however when attempting to compile receive the error:

"C:\Users\David\Documents\Arduino\libraries\ArduinoSTL\extras\uClibc++-OriginalFiles\tests\testframework.h:32:3: error: exception handling disabled, use -fexceptions to enable
   catch (...) {
   ^
make: *** [ArduinoSTL\extras\uClibc++-OriginalFiles\tests/subdir.mk:98: ArduinoSTL\extras\uClibc++-OriginalFiles\tests\algotest.cpp.o] Error 1"

Any ideas of settings or quick fix to make this compatible?

**Comment by mike-matera** [comment]
Your error is that you're trying to compile the test code. Only compile the stuff in the "src" directory.
