### ISSUE TITLE
in file .src\limits  line24  there throw an err 

### ISSUE THREAD

**Issue by noya2012** [mike-matera/ArduinoSTL#62]
in file .src\limits  line24  there throw an err 
but I dont catch the err log,the line detail is:
#warning limits header is nowhere complete or accurate
source：
[https://github.com/mike-matera/ArduinoSTL/blob/master/src/limits](https://github.com/mike-matera/ArduinoSTL/blob/master/src/limits)

the ENV is arduino 1.8.3 
my code is

`#include <ArduinoSTL.h>
#include <vector>
using namespace std;

void Example_Arduino_Blink_LED(){
    /*feedback and shift regs. declarations */
    
    /* END feedback and shift regs declarations */
    bool wireUID_424_ = true;
    bool wireUID_740_A = true;
    long wireUID_705_ = 3;
    long wireUID_652_ = 2;
    pinMode(wireUID_652_,wireUID_740_A?OUTPUT:INPUT);
    pinMode(wireUID_705_,wireUID_740_A?OUTPUT:INPUT);
    /***** BEGIN WhileLoop ********/
    vector< bool > feedbackNode_615;
    bool feedbackNodeInitBool_615 = true;
    
    bool wireUID_430_ = false; //LoopEndRef.
    int iteratorUID_289 = 0; //loop iterator
    do{
     //shift register init and get front value
        /*feedback and shift regs. declarations */
        
        /* END feedback and shift regs declarations */
        bool wireUID_317_B;
        bool wireUID_642_;
        long wireUID_1157_ = 2;
        long wireUID_921_ = 3;
        long wireUID_426_ = 220;
        if (feedbackNodeInitBool_615){
            feedbackNode_615.push_back(wireUID_424_);
            feedbackNodeInitBool_615 = false;
        }
        wireUID_642_ = feedbackNode_615.front(); feedbackNode_615.erase(feedbackNode_615.begin());
        delay(wireUID_426_);
        wireUID_317_B = !wireUID_642_;
        digitalWrite(wireUID_921_,wireUID_642_?HIGH:LOW);
        /* Don't know how to translate class "Generic ->GObject ->Node": "" */
        digitalWrite(wireUID_1157_,wireUID_317_B?HIGH:LOW);
        feedbackNode_615.push_back(wireUID_317_B);
        
        
         //C code
        
         //output assgn.
        iteratorUID_289++; //iterator increment
    }while(!wireUID_430_); //negation because in LabVIEW it is when stop (oposite)
    
    /****** END WhileLoop */
    
    
    
}

void setup(){
    Example_Arduino_Blink_LED();
}
void loop(){
}
`

In my project I removed line 24 then seems OK.

**Comment by mike-matera** [comment]
That warning must stay. It's telling you something important!
