### ISSUE TITLE
Wont compile with VS Code and PlatformIO

### ISSUE THREAD

**Issue by geoffw123** [mike-matera/ArduinoSTL#64]
Hi

I tried your previous STL library, that wouldnt compile, but i saw a comment saying that project was dead and to try this one instead.  So I scrapped that idea and tried this one. Again I get a failure to compile.

#include "ArduinoSTL.h"
void setup() 
{
}

void loop(void)
{
}

In file included from .pio\libdeps\lolin32\ArduinoSTL\src\ArduinoSTL.cpp:2:0:
C:\users\mine\.platformio\packages\framework-arduinoespressif32\cores\esp32/Arduino.h:158:12: error: 'std::isinf' has not been declared

Is this project dead too or not supporting VS Code PlatformIO ?

**Comment by mike-matera** [comment]
This was fixed. Thanks!
