### ISSUE TITLE
Failed compilation of code using ArduinoSTL.h and array on Arduino Uno AVR Boards 1.8.3

### ISSUE THREAD

**Issue by salwaElkaddaoui** [mike-matera/ArduinoSTL#66]
I have written arduino C++ code in which I used std::array quite a lot. Of course I made sure to `#include<ArduinoSTL.h>` and `#include<array>`. The compiler raises multiple compilation errors (see below) without pointing to any line of the code:

`/home/salwa/Arduino/libraries/ArduinoSTL/src/del_opvs.cpp:25:53: error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete[](void * ptr, std::size_t) throw(){
                                                     ^~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/del_ops.cpp:25:50: error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete(void* ptr, std::size_t) throw(){
                                                  ^~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/del_opnt.cpp:25:56: error: 'nothrow_t' in namespace 'std' does not name a type
 _UCXXEXPORT void operator delete(void* ptr, const std::nothrow_t& ) throw() {
                                                        ^~~~~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_opnt.cpp:25:37: error: declaration of 'operator new' as non-function
 _UCXXEXPORT void* operator new(std::size_t numBytes, const std::nothrow_t& ) throw(){
                                     ^~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_opnt.cpp:25:37: error: 'size_t' is not a member of 'std'
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_opnt.cpp:25:37: note: suggested alternative:
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_handler.cpp:22:12: error: 'nothrow_t' in namespace 'std' does not name a type
 const std::nothrow_t std::nothrow = { };
            ^~~~~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_handler.cpp:25:6: error: 'new_handler' in namespace 'std' does not name a type
 std::new_handler __new_handler;
      ^~~~~~~~~~~
/home/salwa/Arduino/libraries/ArduinoSTL/src/new_handler.cpp:27:1: error: '_UCXXEXPORT' does not name a type
`

A similar issue was opened here [https://github.com/mike-matera/ArduinoSTL/issues/56](url), it was suggested to use `#include"ArduinoSTL.h"` instead of `#include<ArduinoSTL.h>`, I did that but it didn't work. I also tried downgrading the AVR boards manager from 1.8.3 to 1.8.2 and to 1.8.1 but that didn't seem to solve the problem.

- Computer kernel/OS: 5.4.0-67-generic #75~18.04.1-Ubuntu
- ArduinoIDE: 1.8.13
- Tested AVR Boards manager: 1.8.1, 1.8.2, 1.8.3 (the problem persists with all these versions)

Any suggestions?

**Comment by dasfdlinux** [comment]
Have you tried using Arduino 1.8.12? I'm also facing issues related to Arduino 1.8.13 and ArduinoSTL, and had to downgrade to 1.8.12 (hopefully temporarily).

**Comment by salwaElkaddaoui** [comment]
@dasfdlinux No I didn't, I rewrote the code using c arrays, but thanks for the suggestion.

**Comment by BCsabaEngine** [comment]
Waiting for... and thanks!

**Comment by blackpancake** [comment]
The same issue here.
![image](https://user-images.githubusercontent.com/62934143/124452517-09522a00-ddb9-11eb-8ec6-6ac5c536e766.png)

**Comment by chrisflesher** [comment]
Same issue:
Arduino IDE version: 1.8.13
ArduinoSTL version: 1.1.0
Platform: Ubuntu 20.04

**Comment by kleurbleur** [comment]
Some problem here.

Arduino IDE version: 1.8.15, 1.8.13, 1.8.12
ArduinoSTL version: 1.1.0
Platform: MacOS 10.15.7

**Comment by ZhongKang97** [comment]
Same issue.

Arduino IDE version: 1.8.16
ArduinoSTL version: 1.1.0
Platform: Windows10 + VS2019
![image](https://user-images.githubusercontent.com/47888587/134017671-ee20b62f-4c25-4661-a9fd-2e0f2ae4ca81.png)

**Comment by mike-matera** [comment]
It's fixed now! Thank you.

**Comment by BCsabaEngine** [comment]
We will try it. Thx!!!
