### ISSUE TITLE
ISO C++1z does not allow dynamic exception specifications error

### ISSUE THREAD

**Issue by FUEL4EP** [mike-matera/ArduinoSTL#67]
When trying compile an Arduino code with IDE 1.8.13 I am getting the error message

ArduinoSTL/src/new:40:54: error: ISO C++1z does not allow dynamic exception specifications
 _UCXXEXPORT void* operator new(std::size_t numBytes) throw(std::bad_alloc);

How to overcome this?

**Comment by mike-matera** [comment]
This is fixed in the latest version. Thank you!
