### ISSUE TITLE
Support for unordered_map

### ISSUE THREAD

**Issue by rosshadden** [mike-matera/ArduinoSTL#7]
I noticed not all of the STL types are present, like `unordered_map` for example.  Are these planned for the future?

**Comment by mike-matera** [comment]
Hi! 

Thanks for the comment. Most of the STL comes from the upstream project:

https://git.uclibc.org/uClibc++

That's the right place to ask for STL features. I've sent them patches to them but I never heard back. According to their git they're still developing so I don't want to make too many changes that might conflict with upstream. Sorry!

**Comment by rosshadden** [comment]
Okay, thanks for the explanation.
