### ISSUE TITLE
C++11 smart pointers support

### ISSUE THREAD

**Issue by ilann** [mike-matera/ArduinoSTL#8]
Any plans for that?

**Comment by mike-matera** [comment]
Hi. No plans at the moment. I'm always interested in pull requests!

**Comment by wvlia5** [comment]
Interested in this too

**Comment by mike-matera** [comment]
Yes, uCLibc++ is the right place for the feature. I'm very hesitant to get too far away from upstream and I try to confine my changes to bug fixes and features that are essential for teaching my class. 

The emGUI project is tested on an esp8266, which is a Tensilica processor, not an AVR. The Tenscilica GCC toolchain contains a native STL implementation so you don't need ArduinoSTL.
