### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Erutan409** [mike-matera/ArduinoSTL#9]
Thank you for your work on this library.  When I swapped out [StandardCplusplus](https://github.com/SGSSGene/StandardCplusplus) for your's, I noticed an almost 20% increase in memory requirements.  Is this normal and/or expected?  Seems like this will be problematic for me using one of my Uno's.

**Comment by mike-matera** [comment]
The configuration that I use is somewhat maximal. If you configure uClibC++ differently it cuts out a lot of stuff you might not need.
